version: '3'

services:

  app: 
    build: ./
    env_file: 
      - .env
    container_name: app-collect-metrics
    networks:
      - app-network
    depends_on:
      - "mongo"

  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=metrics_api_gateway
    ports: 
     - 27017:27017
    networks:
      - app-network

networks:
  app-network:
    driver: bridge